# Generated by Django 2.2.28 on 2024-01-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20240129_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
